create table if not exists public.trade_events (
  id bigint generated by default as identity primary key,
  event_id text not null,
  event_time_utc timestamptz not null,
  event_type text not null,
  symbol text not null,
  underlying_symbol text,
  signal_id text,
  trade_id text,
  parent_event_id text,
  mode text not null,
  is_test boolean not null default false,
  strategy text,
  engine text,
  side text,
  source text not null,
  notes text,
  payload jsonb not null default '{}'::jsonb,
  producer text,
  schema_version text,
  received_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'trade_events_event_id_key'
  ) then
    alter table public.trade_events
      add constraint trade_events_event_id_key unique (event_id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'trade_events_mode_check'
  ) then
    alter table public.trade_events
      add constraint trade_events_mode_check
      check (mode in ('live', 'paper', 'test'));
  end if;
end
$$;

create index if not exists trade_events_event_time_idx
  on public.trade_events (event_time_utc desc);

create index if not exists trade_events_event_type_idx
  on public.trade_events (event_type);

create index if not exists trade_events_signal_id_idx
  on public.trade_events (signal_id);

create index if not exists trade_events_trade_id_idx
  on public.trade_events (trade_id);

create index if not exists trade_events_symbol_idx
  on public.trade_events (symbol);

create index if not exists trade_events_source_idx
  on public.trade_events (source);
